function spacingBasket = calcSpacing(domains)
%CALCSPACING for each dimension of data calculates the spacing in domains,
%which are generated by meshgrid

spacingBasket = cell(numel(domains),1);
sizeData = size(domains{1});
cumProdSize = [0 cumprod(sizeData)];
% 2,1,1  nx = 2 + (1 -1).*siz(1) + (1-1)*siz(2)*siz(3)
% 1 2,1  nx = 1+ (2 - 1).*siz(1) + (1-1)*siz(2)*siz(3)
% 1 1 2  nx = 1 + (1 - 1).*size(2) + (2-1)*size(2)*size(1)

for ii = 1:numel(spacingBasket)
    if ii ==1
        nx = 2;
    else
        nx = 1 + cumProdSize(ii);
    end
    spacingBasket{ii} = domains{ii}(nx) - domains{ii}(1);
end

% for ii = 1:numel(spacingBasket)
%    currDomain = domains{ii};
%    for jj = 1:ndims(currDomain)
%       diffDomain = diff(currDomain,1,jj);
%       theDiffs = uniqueFP(diffDomain,10^-10);
%       if numel(theDiffs) > 1
%          error('this domain has uneven spacing');
%       end
%       if theDiffs > 0
%          spacingBasket{ii} =  theDiffs;
%       end
%    end
% end


end

