function [ minMaxes ] = calcMinMaxFromMeshData(domains )
%CALCMINMAXFROMMESHDATA given a list of domains generated by ndGrid, find
%the min and max values

minMaxes = zeros(numel(domains),2);

for ii = 1:numel(domains)
   minMaxes(ii,:) = [min(domains{ii}(:)) max(domains{ii}(:))] ;
end
end

